//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computers.PowerSupply {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PowerSupply.SPowerSupply")]
    public interface SPowerSupply {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/NewPowerSupply", ReplyAction="http://tempuri.org/SPowerSupply/NewPowerSupplyResponse")]
        void NewPowerSupply(string manufacturer, string model, string power);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/NewPowerSupply", ReplyAction="http://tempuri.org/SPowerSupply/NewPowerSupplyResponse")]
        System.Threading.Tasks.Task NewPowerSupplyAsync(string manufacturer, string model, string power);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/Save", ReplyAction="http://tempuri.org/SPowerSupply/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/Save", ReplyAction="http://tempuri.org/SPowerSupply/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/Update", ReplyAction="http://tempuri.org/SPowerSupply/UpdateResponse")]
        void Update(string manufacturer, string newmodel, string power, string oldmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/Update", ReplyAction="http://tempuri.org/SPowerSupply/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string manufacturer, string newmodel, string power, string oldmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/delete", ReplyAction="http://tempuri.org/SPowerSupply/deleteResponse")]
        void delete(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/delete", ReplyAction="http://tempuri.org/SPowerSupply/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/toString", ReplyAction="http://tempuri.org/SPowerSupply/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/toString", ReplyAction="http://tempuri.org/SPowerSupply/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/get", ReplyAction="http://tempuri.org/SPowerSupply/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPowerSupply/get", ReplyAction="http://tempuri.org/SPowerSupply/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPowerSupplyChannel : Computers.PowerSupply.SPowerSupply, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPowerSupplyClient : System.ServiceModel.ClientBase<Computers.PowerSupply.SPowerSupply>, Computers.PowerSupply.SPowerSupply {
        
        public SPowerSupplyClient() {
        }
        
        public SPowerSupplyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPowerSupplyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPowerSupplyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPowerSupplyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewPowerSupply(string manufacturer, string model, string power) {
            base.Channel.NewPowerSupply(manufacturer, model, power);
        }
        
        public System.Threading.Tasks.Task NewPowerSupplyAsync(string manufacturer, string model, string power) {
            return base.Channel.NewPowerSupplyAsync(manufacturer, model, power);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public void Update(string manufacturer, string newmodel, string power, string oldmodel) {
            base.Channel.Update(manufacturer, newmodel, power, oldmodel);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string manufacturer, string newmodel, string power, string oldmodel) {
            return base.Channel.UpdateAsync(manufacturer, newmodel, power, oldmodel);
        }
        
        public void delete(string model) {
            base.Channel.delete(model);
        }
        
        public System.Threading.Tasks.Task deleteAsync(string model) {
            return base.Channel.deleteAsync(model);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
    }
}
