//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computers.Housing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Housing.SHousing")]
    public interface SHousing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/NewHousing", ReplyAction="http://tempuri.org/SHousing/NewHousingResponse")]
        void NewHousing(string manufacturer, string model, string color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/NewHousing", ReplyAction="http://tempuri.org/SHousing/NewHousingResponse")]
        System.Threading.Tasks.Task NewHousingAsync(string manufacturer, string model, string color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/Save", ReplyAction="http://tempuri.org/SHousing/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/Save", ReplyAction="http://tempuri.org/SHousing/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/Update", ReplyAction="http://tempuri.org/SHousing/UpdateResponse")]
        void Update(string manufacturer, string newmodel, string color, string oldmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/Update", ReplyAction="http://tempuri.org/SHousing/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string manufacturer, string newmodel, string color, string oldmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/delete", ReplyAction="http://tempuri.org/SHousing/deleteResponse")]
        void delete(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/delete", ReplyAction="http://tempuri.org/SHousing/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/toString", ReplyAction="http://tempuri.org/SHousing/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/toString", ReplyAction="http://tempuri.org/SHousing/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/get", ReplyAction="http://tempuri.org/SHousing/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHousing/get", ReplyAction="http://tempuri.org/SHousing/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SHousingChannel : Computers.Housing.SHousing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SHousingClient : System.ServiceModel.ClientBase<Computers.Housing.SHousing>, Computers.Housing.SHousing {
        
        public SHousingClient() {
        }
        
        public SHousingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SHousingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SHousingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SHousingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewHousing(string manufacturer, string model, string color) {
            base.Channel.NewHousing(manufacturer, model, color);
        }
        
        public System.Threading.Tasks.Task NewHousingAsync(string manufacturer, string model, string color) {
            return base.Channel.NewHousingAsync(manufacturer, model, color);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public void Update(string manufacturer, string newmodel, string color, string oldmodel) {
            base.Channel.Update(manufacturer, newmodel, color, oldmodel);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string manufacturer, string newmodel, string color, string oldmodel) {
            return base.Channel.UpdateAsync(manufacturer, newmodel, color, oldmodel);
        }
        
        public void delete(string model) {
            base.Channel.delete(model);
        }
        
        public System.Threading.Tasks.Task deleteAsync(string model) {
            return base.Channel.deleteAsync(model);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
    }
}
