//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computers.Videocard {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Videocard.SVideocard")]
    public interface SVideocard {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/NewVideocard", ReplyAction="http://tempuri.org/SVideocard/NewVideocardResponse")]
        void NewVideocard(string manufacturer, string model, string memory, string clock_Freq, string memory_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/NewVideocard", ReplyAction="http://tempuri.org/SVideocard/NewVideocardResponse")]
        System.Threading.Tasks.Task NewVideocardAsync(string manufacturer, string model, string memory, string clock_Freq, string memory_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/Save", ReplyAction="http://tempuri.org/SVideocard/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/Save", ReplyAction="http://tempuri.org/SVideocard/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/Update", ReplyAction="http://tempuri.org/SVideocard/UpdateResponse")]
        void Update(string manufacturer, string newmodel, string memory, string clock_Freq, string memory_type, string oldmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/Update", ReplyAction="http://tempuri.org/SVideocard/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string manufacturer, string newmodel, string memory, string clock_Freq, string memory_type, string oldmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/delete", ReplyAction="http://tempuri.org/SVideocard/deleteResponse")]
        void delete(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/delete", ReplyAction="http://tempuri.org/SVideocard/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/toString", ReplyAction="http://tempuri.org/SVideocard/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/toString", ReplyAction="http://tempuri.org/SVideocard/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/get", ReplyAction="http://tempuri.org/SVideocard/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SVideocard/get", ReplyAction="http://tempuri.org/SVideocard/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SVideocardChannel : Computers.Videocard.SVideocard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SVideocardClient : System.ServiceModel.ClientBase<Computers.Videocard.SVideocard>, Computers.Videocard.SVideocard {
        
        public SVideocardClient() {
        }
        
        public SVideocardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SVideocardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SVideocardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SVideocardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewVideocard(string manufacturer, string model, string memory, string clock_Freq, string memory_type) {
            base.Channel.NewVideocard(manufacturer, model, memory, clock_Freq, memory_type);
        }
        
        public System.Threading.Tasks.Task NewVideocardAsync(string manufacturer, string model, string memory, string clock_Freq, string memory_type) {
            return base.Channel.NewVideocardAsync(manufacturer, model, memory, clock_Freq, memory_type);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public void Update(string manufacturer, string newmodel, string memory, string clock_Freq, string memory_type, string oldmodel) {
            base.Channel.Update(manufacturer, newmodel, memory, clock_Freq, memory_type, oldmodel);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string manufacturer, string newmodel, string memory, string clock_Freq, string memory_type, string oldmodel) {
            return base.Channel.UpdateAsync(manufacturer, newmodel, memory, clock_Freq, memory_type, oldmodel);
        }
        
        public void delete(string model) {
            base.Channel.delete(model);
        }
        
        public System.Threading.Tasks.Task deleteAsync(string model) {
            return base.Channel.deleteAsync(model);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
    }
}
